brendan = User.create(first_name: 'Brendan', last_name: 'Humphries', username: 'bren2233', email: 'brendan.b.humphries@gmail.com', password: 'Juliette')
brendan.profile_photo.attach(io: File.open(Rails.root.join('app/assets/images/Brendan Profile.JPG')), filename: 'Brendan Profile.JPG')
regina = User.create(first_name: 'Regina', last_name: 'Buttner', username: 'ReginaOnEmery', email: 'reginabuttner@yahoo.com', password: 'Pekoe')
regina.profile_photo.attach(io: File.open(Rails.root.join('app/assets/images/Regina Profile.JPG')), filename: 'Regina Profile.JPG')
bradley = User.create(first_name: 'Bradley', last_name: 'Humphries', username: 'Madley', email: 'bradleyhumphries@gmail.com', password: 'Birdie')
bradley.profile_photo.attach(io: File.open(Rails.root.join('app/assets/images/Bradley Profile.JPG')), filename: 'Bradley Profile.JPG')
jesse = User.create(first_name: 'Jesse', last_name: 'Harlan', username: 'JesseHarlan', email: 'Jesse@flatiron.com', password: 'Jesse')
jesse.profile_photo.attach(io: File.open(Rails.root.join('app/assets/images/Jesse Profile.jpg')), filename: 'Jesse Profile.jpg')
joshua = User.create(first_name: 'Joshua', last_name: 'Andes', username: 'JoshAndes', email: 'Joshua@flatiron.com', password: 'Joshua')
joshua.profile_photo.attach(io: File.open(Rails.root.join('app/assets/images/Josh Profile.jpg')), filename: 'Josh Profile.jpg')
william = User.create(first_name: 'William', last_name: 'Gotterer', username: 'WillGotterer', email: 'William@flatiron.com', password: 'William')
william.profile_photo.attach(io: File.open(Rails.root.join('app/assets/images/William Profile.jpg')), filename: 'William Profile.jpg')

juliette = Dog.create(user_id: brendan.id, name: 'Juliette', breed: 'Golden Retriever', sex: 'female', age: 8, favorite_activity: 'Cuddling', favorite_food: 'Apple Cores')
juliette.profile_photo.attach(io: File.open(Rails.root.join('app/assets/images/Juliette Profile.JPG')), filename: 'Juliette Profile.JPG')
pekoe = Dog.create(user_id: regina.id, name: 'Pekoe', breed: 'Corgi', sex: 'female', age: 1, favorite_activity: 'Being a loaf', favorite_food: 'Peanut Butter')
pekoe.profile_photo.attach(io: File.open(Rails.root.join('app/assets/images/Pekoe Profile.jpg')), filename: 'Pekoe Profile.jpg')
birdie = Dog.create(user_id: bradley.id, name: 'Birdie', breed: 'Australian Labradoodle', sex: 'female', age: 1, favorite_activity: 'Biting everything', favorite_food: 'Toes')
birdie.profile_photo.attach(io: File.open(Rails.root.join('app/assets/images/Birdie Profile.JPG')), filename: 'Birdie Profile.JPG')
cassidy = Dog.create(user_id: jesse.id, name: 'Cassidy', breed: 'Pit Mix', sex: 'female', age: 8, favorite_activity: 'Cuddling', favorite_food: 'Stella & Chewy Meal Mixers')
cassidy.profile_photo.attach(io: File.open(Rails.root.join('app/assets/images/Cassidy Gaming.jpg')), filename: 'Cassidy Gaming.jpg')
sally = Dog.create(user_id: jesse.id, name: 'Sally', breed: 'Mini Bernedoodle', sex: 'female', age: 1, favorite_activity: 'Chasing leaves in the wind', favorite_food: 'Literally anything')
sally.profile_photo.attach(io: File.open(Rails.root.join('app/assets/images/Sally Sitting.jpg')), filename: 'Sally Sitting.jpg')
joey = Dog.create(user_id: jesse.id, name: 'Joey', breed: 'Chihuahua', sex: 'male', age: 2, favorite_activity: 'Peeing inside', favorite_food: 'Rawhides')
joey.profile_photo.attach(io: File.open(Rails.root.join('app/assets/images/Joey Profile.jpg')), filename: 'Joey Profile.jpg')
titus = Dog.create(user_id: joshua.id, name: 'Titus', breed: 'Boston Terrier/Pitbull', sex: 'male', age: 6, favorite_activity: 'Tug O\' War', favorite_food: 'Peanut Butter')
titus.profile_photo.attach(io: File.open(Rails.root.join('app/assets/images/Titus Profile.jpg')), filename: 'Titus Profile.jpg')
catdog = Dog.create(user_id: william.id, name: 'CatDog', breed: 'Mutt', sex: 'male?', age: 23, favorite_activity: 'Running around', favorite_food: 'Bones')
catdog.profile_photo.attach(io: File.open(Rails.root.join('app/assets/images/CatDog Profile.jpg')), filename: 'CatDog Profile.jpg')

Friend.create(dog_id: juliette.id, friend_id: pekoe.id)
Friend.create(dog_id: juliette.id, friend_id: birdie.id)
Friend.create(dog_id: juliette.id, friend_id: cassidy.id)
Friend.create(dog_id: juliette.id, friend_id: sally.id)
Friend.create(dog_id: juliette.id, friend_id: titus.id)
Friend.create(dog_id: juliette.id, friend_id: catdog.id)
Friend.create(dog_id: pekoe.id, friend_id: juliette.id)
Friend.create(dog_id: birdie.id, friend_id: juliette.id)
Friend.create(dog_id: cassidy.id, friend_id: sally.id)
Friend.create(dog_id: cassidy.id, friend_id: juliette.id)
Friend.create(dog_id: cassidy.id, friend_id: titus.id)
Friend.create(dog_id: sally.id, friend_id: cassidy.id)
Friend.create(dog_id: sally.id, friend_id: juliette.id)
Friend.create(dog_id: sally.id, friend_id: titus.id)
Friend.create(dog_id: catdog.id, friend_id: juliette.id)

juliettePost1 = Post.create(dog_id: juliette.id, post_text: 'Felt cute, might delete later', location: 'Heaven')
juliettePost1.photo.attach(io: File.open(Rails.root.join('app/assets/images/Juliette Teefs.JPG')), filename: 'Juliette Teefs.JPG')
juliettePost2 = Post.create(dog_id: juliette.id, post_text: 'Ready for another day as a Get Swole Trainer!', location: 'Get Swole Online Gym')
juliettePost2.photo.attach(io: File.open(Rails.root.join('app/assets/images/Juliette Trainer.JPG')), filename: 'Juliette Trainer.JPG')
juliettePost3 = Post.create(dog_id: juliette.id, post_text: 'This is my favorite toy!', location: 'The Living Room')
juliettePost3.photo.attach(io: File.open(Rails.root.join('app/assets/images/Juliette Puppy.JPG')), filename: 'Juliette Puppy.JPG')

pekoePost1 = Post.create(dog_id: pekoe.id, post_text: 'I think my human put my legs on backwards! Help!', location: 'The Upsidedown')
pekoePost1.photo.attach(io: File.open(Rails.root.join('app/assets/images/Pekoe Post.jpg')), filename: 'Pekoe Post.jpg')
pekoePost2 = Post.create(dog_id: pekoe.id, post_text: 'Time for a lazy day, everyone needs a break', location: 'The Couch')
pekoePost2.photo.attach(io: File.open(Rails.root.join('app/assets/images/Pekoe Couch.JPG')), filename: 'Pekoe Couch.JPG')
pekoePost3 = Post.create(dog_id: pekoe.id, post_text: 'Basking in the Florida sun!', location: 'Fort Myers, FL')
pekoePost3.photo.attach(io: File.open(Rails.root.join('app/assets/images/Pekoe Sun.JPG')), filename: 'Pekoe Sun.JPG')

birdiePost1 = Post.create(dog_id: birdie.id, post_text: 'Let me out of jail!', location: 'Alcatraz Penitentiary')
birdiePost1.photo.attach(io: File.open(Rails.root.join('app/assets/images/Birdie Jail.JPG')), filename: 'Birdie Jail.jpg')
birdiePost2 = Post.create(dog_id: birdie.id, post_text: 'Ahh, this is the perfect place to rest my head', location: 'The Kitchen')
birdiePost2.photo.attach(io: File.open(Rails.root.join('app/assets/images/Birdie Chair.JPG')), filename: 'Birdie Chair.JPG')
birdiePost3 = Post.create(dog_id: birdie.id, post_text: 'The beach can be scary sometimes!', location: 'The Beach')
birdiePost3.photo.attach(io: File.open(Rails.root.join('app/assets/images/Birdie Beach.JPG')), filename: 'Birdie Beach.JPG')

cassidyPost1 = Post.create(dog_id: cassidy.id, post_text: "I'm a lion! Rawr!", location: 'The Serengeti')
cassidyPost1.photo.attach(io: File.open(Rails.root.join('app/assets/images/Cassidy Cone.jpg')), filename: 'Cassidy Cone.jpg')
cassidyPost2 = Post.create(dog_id: cassidy.id, post_text: 'Somebody has to keep watch!', location: 'The Window')
cassidyPost2.photo.attach(io: File.open(Rails.root.join('app/assets/images/Cassidy & Sally Window.jpg')), filename: 'Cassidy & Sally Window.jpg')
Tag.create(post_id: cassidyPost2, tag_id: sally)
cassidyPost3 = Post.create(dog_id: cassidy.id, post_text: 'Road trip with my bestie!', location: 'The Backseat')
cassidyPost3.photo.attach(io: File.open(Rails.root.join('app/assets/images/Cassidy & Sally Car.jpg')), filename: 'Cassidy & Sally Car.jpg')
Tag.create(post_id: cassidyPost3, tag_id: sally)

sallyPost1 = Post.create(dog_id: sally.id, post_text: 'This blanket is delicious!', location: 'The Couch')
sallyPost1.photo.attach(io: File.open(Rails.root.join('app/assets/images/Sally Sitting.jpg')), filename: 'Sally Sitting.jpg')
sallyPost2 = Post.create(dog_id: sally.d, post_text: 'This is my buddy! I put a pillow on her head!', location: 'The Bed')
Tag.create(post_id: sallyPost2, tag_id: cassidy)
sallyPost3 = Post.create(dog_id: sally.id, post_text: 'Cone of shame? More like cone of fame!', location: 'The Frog Pond')
sallyPost3.photo.attach(io: File.open(Rails.root.join('app/assets/images/Sally Cone.jpg')), filename: 'Sally Cone.jpg')
sallyPost4 = Post.create(dog_id: sally.id, post_text: 'Sometimes you just gotta snooze with your friend', location: 'Dreamland')
sallyPost4.photo.attach(io: File.open(Rails.root.join('app/assets/images/Cassidy & Sally Couch.jpg')), filename: 'Cassidy & Sally Couch.jpg')
Tag.create(post_id: sallyPost4, tag_id: cassidy)

joeyPost1= Post.create(dog_id: joey.id, post_text: 'Just chilling with the dog squad!', location: 'The Dog Park')
joeyPost1.photo.attach(io: File.open(Rails.root.join('app/assets/images/Joey Post.jpg')), filename: 'Joey Post.jpg')
Tag.create(post_id: joeyPost1, tag_id: cassidy)
Tag.create(post_id: joeyPost1, tag_id: sally)

titusPost1 = Post.create(dog_id: titus.id, post_text: 'Owner is annoying me w hat, might chew hat later', location: 'The Couch')
titusPost1.photo.attach(io: File.open(Rails.root.join('app/assets/images/Titus Post.jpg')), filename: 'Titus Post.jpg')

catdogPost1 = Post.create(dog_id: catdog.id, post_text: 'Lets party', location: 'The Club')
catdogPost1.photo.attach(io: File.open(Rails.root.join('app/assets/images/CatDog Post.jpeg')), filename: 'CatDog Post.jpeg')